/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return liveness without opening a database connection.
         */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_v1_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research-workflow-map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research Workflow Map */
        get: operations["research_workflow_map_api_v1_research_workflow_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/achievement-cards/{card_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Achievement Attachment */
        post: operations["upload_achievement_attachment_api_v1_achievement_cards__card_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/achievement-attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Achievement Attachment Detail */
        get: operations["achievement_attachment_detail_api_v1_achievement_attachments__attachment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/achievement-attachments/{attachment_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Achievement Attachment */
        get: operations["download_achievement_attachment_api_v1_achievement_attachments__attachment_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/achievement-attachments/{attachment_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Achievement Attachment */
        get: operations["preview_achievement_attachment_api_v1_achievement_attachments__attachment_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/achievement-attachments/{attachment_id}/images/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Achievement Attachment Image */
        get: operations["achievement_attachment_image_api_v1_achievement_attachments__attachment_id__images__index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{context_id}/deletion/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Context Deletion */
        post: operations["prepare_context_deletion_api_v1_contexts__context_id__deletion_prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{context_id}/deletion/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Context Deletion */
        post: operations["commit_context_deletion_api_v1_contexts__context_id__deletion_commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contexts */
        get: operations["list_contexts_api_v1_contexts_get"];
        put?: never;
        /** Create Context */
        post: operations["create_context_api_v1_contexts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{context_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Context Detail */
        get: operations["context_detail_api_v1_contexts__context_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{context_id}/disclosure-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Disclosure Preferences */
        get: operations["get_disclosure_preferences_api_v1_contexts__context_id__disclosure_preferences_get"];
        put?: never;
        /** Upsert Disclosure Preference */
        post: operations["upsert_disclosure_preference_api_v1_contexts__context_id__disclosure_preferences_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ui/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Ui Session */
        post: operations["create_ui_session_api_v1_ui_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/completion-authorization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Completion Authorization */
        post: operations["create_completion_authorization_api_v1_workflows__workflow_id__completion_authorization_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{context_id}/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Context Workflows */
        get: operations["context_workflows_api_v1_contexts__context_id__workflows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/achievement-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Achievement Card */
        post: operations["create_achievement_card_api_v1_achievement_cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/achievement-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Achievement Card Compat */
        post: operations["create_achievement_card_compat_api_achievement_cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/achievement-cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Achievement Card */
        put: operations["update_achievement_card_api_v1_achievement_cards__card_id__put"];
        post?: never;
        /** Delete Achievement Card */
        delete: operations["delete_achievement_card_api_v1_achievement_cards__card_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{context_id}/workflows/{workflow_id}/achievement-cards/{card_id}/importance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Achievement Card Importance */
        patch: operations["set_achievement_card_importance_api_v1_contexts__context_id__workflows__workflow_id__achievement_cards__card_id__importance_patch"];
        trace?: never;
    };
    "/api/v1/contexts/{context_id}/workflow-selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Workflow Selection */
        post: operations["set_workflow_selection_api_v1_contexts__context_id__workflow_selection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/completion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Workflow Completion */
        post: operations["set_workflow_completion_api_v1_workflows__workflow_id__completion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AchievementAttachmentDTO
         * @description Safe attachment descriptor exposed by native workbench endpoints.
         */
        AchievementAttachmentDTO: {
            /** Id */
            id: string;
            /** Card Id */
            card_id: string;
            /** Original Name */
            original_name: string;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /** Preview State */
            preview_state: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Row Version */
            row_version: number;
            /** Settings Version */
            settings_version: number;
            /** Path Schema Version */
            path_schema_version: number;
            /** Area Name Snapshot */
            area_name_snapshot?: string | null;
            /** Work Package Name Snapshot */
            work_package_name_snapshot?: string | null;
            /** Event Folder Snapshot */
            event_folder_snapshot?: string | null;
            /** Preview Error */
            preview_error?: string | null;
        };
        /**
         * AchievementCardDTO
         * @description Legacy card response shape including its (empty in P2A) attachment array.
         */
        AchievementCardDTO: {
            /** Id */
            id: string;
            /** Context Id */
            context_id: string;
            /** Workflow Id */
            workflow_id: string;
            /** Work Package Id */
            work_package_id: string;
            /** Week Item Id */
            week_item_id: string | null;
            /** Event Date */
            event_date: string;
            /** Event Name */
            event_name: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /** Is Important */
            is_important: boolean;
            /** Row Version */
            row_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Attachments */
            attachments: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
        };
        /**
         * AchievementCardDeleteDTO
         * @description Delete input requiring the legacy explicit confirmation token.
         */
        AchievementCardDeleteDTO: {
            /** @default author */
            actor: components["schemas"]["JsonValue"];
            confirmation_token?: components["schemas"]["JsonValue"] | null;
            /** @default 0 */
            expected_version: components["schemas"]["JsonValue"];
        };
        /**
         * AchievementCardImportanceDTO
         * @description Importance input preserving the legacy boolean coercion boundary.
         */
        AchievementCardImportanceDTO: {
            /** @default false */
            is_important: components["schemas"]["JsonValue"];
            /** @default 0 */
            expected_version: components["schemas"]["JsonValue"];
            /** @default author */
            actor: components["schemas"]["JsonValue"];
            idempotency_key?: components["schemas"]["JsonValue"] | null;
        };
        /**
         * AchievementCardUpdateDTO
         * @description Legacy-compatible edit input with route-edge string coercion.
         */
        AchievementCardUpdateDTO: {
            /** @default  */
            event_date: components["schemas"]["JsonValue"];
            /** @default  */
            event_name: components["schemas"]["JsonValue"];
            /** @default  */
            description: components["schemas"]["JsonValue"];
            /** @default 0 */
            expected_version: components["schemas"]["JsonValue"];
            /** @default author */
            actor: components["schemas"]["JsonValue"];
        };
        /**
         * CardDeleteResultDTO
         * @description Exact legacy delete response fields.
         */
        CardDeleteResultDTO: {
            /** Id */
            id: string;
            /** Deleted */
            deleted: boolean;
            /** Context Id */
            context_id: string;
            /** Workflow Id */
            workflow_id: string;
        };
        /**
         * CardImportanceResultDTO
         * @description Exact legacy importance response fields.
         */
        CardImportanceResultDTO: {
            /** Card Id */
            card_id: string;
            /** Is Important */
            is_important: boolean;
            /** Changed */
            changed: boolean;
            /** Row Version */
            row_version: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Operation Id */
            operation_id: string;
        };
        /** CatalogAreaDTO */
        CatalogAreaDTO: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Work Packages */
            work_packages: components["schemas"]["WorkPackageDTO"][];
        };
        /** CatalogDTO */
        CatalogDTO: {
            /** Version */
            version: string;
            /** Areas */
            areas: components["schemas"]["CatalogAreaDTO"][];
        };
        /** CompletionAuthorizationResultDTO */
        CompletionAuthorizationResultDTO: {
            /** Nonce Id */
            nonce_id: string;
            /** Nonce Hash */
            nonce_hash: string;
            /** Session Id */
            session_id: string;
            /** Workflow Id */
            workflow_id: string;
            /** Expected Version */
            expected_version: number;
            /** Operation */
            operation: string;
            /** Expires At */
            expires_at: number;
            /** Context Id */
            context_id: string;
            /** Work Package Id */
            work_package_id: string;
        };
        /**
         * ContextDTO
         * @description Context row shape returned by the legacy list endpoint.
         */
        ContextDTO: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Problem */
            problem: string;
            /** Goal */
            goal: string;
            /** Owner */
            owner: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Row Version */
            row_version: number;
            /** Lifecycle State */
            lifecycle_state: string;
        };
        /**
         * ContextDeletionCommitDTO
         * @description Consume a prepared deletion ticket exactly once.
         */
        ContextDeletionCommitDTO: {
            /** @default  */
            operation_id: components["schemas"]["JsonValue"];
            /** @default  */
            confirmation: components["schemas"]["JsonValue"];
            /** @default  */
            session_id: components["schemas"]["JsonValue"];
        };
        /** ContextDeletionCommitResultDTO */
        ContextDeletionCommitResultDTO: {
            /** Operation Id */
            operation_id: string;
            /** State */
            state: string;
            /** Retain Files */
            retain_files: boolean;
            /**
             * Idempotent
             * @default false
             */
            idempotent: boolean;
            /**
             * Removed Attachment Count
             * @default 0
             */
            removed_attachment_count: number;
            /** Manifest Ref */
            manifest_ref?: string | null;
            /**
             * Unresolved Files
             * @default []
             */
            unresolved_files: string[];
        };
        /**
         * ContextDeletionPrepareDTO
         * @description Prepare a session-bound, one-time Context deletion ticket.
         */
        ContextDeletionPrepareDTO: {
            /** @default true */
            retain_files: components["schemas"]["JsonValue"];
            /** @default 0 */
            expected_version: components["schemas"]["JsonValue"];
            /** @default  */
            session_id: components["schemas"]["JsonValue"];
        };
        /**
         * ContextDeletionPrepareResultDTO
         * @description Impact snapshot plus a confirmation token that is never persisted raw.
         */
        ContextDeletionPrepareResultDTO: {
            /** Operation Id */
            operation_id: string;
            /** Request Id */
            request_id: string;
            /** Context Id */
            context_id: string;
            /** Context Name */
            context_name: string;
            /** Retain Files */
            retain_files: boolean;
            /** Expected Version */
            expected_version: number;
            /** Confirmation */
            confirmation: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Entity Counts */
            entity_counts: {
                [key: string]: number;
            };
            /** Attachments */
            attachments: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Manifest Digest */
            manifest_digest: string;
            /** State */
            state: string;
        };
        /** ContextListDTO */
        ContextListDTO: {
            /** Contexts */
            contexts: components["schemas"]["ContextDTO"][];
        };
        /**
         * CreatedContextDTO
         * @description Exact fields returned by the legacy context create command.
         */
        CreatedContextDTO: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Problem */
            problem: string;
            /** Goal */
            goal: string;
            /** Owner */
            owner: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DisclosurePreferenceDTO
         * @description One Context disclosure object and its optimistic-lock version.
         */
        DisclosurePreferenceDTO: {
            /** Context Id */
            context_id: string;
            /** Disclosure Kind */
            disclosure_kind: string;
            /** Stable Subject Id */
            stable_subject_id: string;
            /** Is Expanded */
            is_expanded: boolean;
            /** Row Version */
            row_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DisclosurePreferenceListDTO */
        DisclosurePreferenceListDTO: {
            /** Context Id */
            context_id: string;
            /** Local User Key */
            local_user_key: string;
            /** Preferences */
            preferences: components["schemas"]["DisclosurePreferenceDTO"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        JsonValue: unknown;
        /**
         * ProgressDTO
         * @description Legacy progress projection; warning variants intentionally remain JSON-typed.
         */
        ProgressDTO: {
            /** Context Id */
            context_id: string;
            /** Total */
            total: number;
            /** Completed */
            completed: number;
            /** Ratio */
            ratio: number | null;
            /** Expected Total */
            expected_total: number;
            /** Snapshot Incomplete */
            snapshot_incomplete: boolean;
            /** Warnings */
            warnings: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Missing Work Package Ids */
            missing_work_package_ids: string[];
            /** Extra Work Package Ids */
            extra_work_package_ids: string[];
            /** Unassigned Work Package Ids */
            unassigned_work_package_ids: string[];
            /** Areas */
            areas: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Workflows */
            workflows: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
        };
        /** ReadinessDTO */
        ReadinessDTO: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /**
         * ResearchWorkflowDTO
         * @description Public AI4SCIENCE workflow boundary; it is not a context workflow row.
         */
        ResearchWorkflowDTO: {
            /** Id */
            id: string;
            /** Stage */
            stage: string;
            /** Stage Name */
            stage_name: string;
            /** Name */
            name: string;
            /** Owner Role */
            owner_role: string;
            /** Description */
            description: string;
            /** Outputs */
            outputs: string[];
            /** Work Package Ids */
            work_package_ids: string[];
        };
        /** ResearchWorkflowMapDTO */
        ResearchWorkflowMapDTO: {
            /** Version */
            version: string;
            /** Workflows */
            workflows: components["schemas"]["ResearchWorkflowDTO"][];
        };
        /** UiSessionIssueResultDTO */
        UiSessionIssueResultDTO: {
            /** Session Id */
            session_id: string;
            /** Expires At */
            expires_at: number;
            /** Actor */
            actor: string;
            /** Display Label */
            display_label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkPackageDTO
         * @description Public work package contract; nested catalog assets remain JSON-typed.
         */
        WorkPackageDTO: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Action */
            action: string;
            /** Deliverable */
            deliverable: string;
            /** Template */
            template: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Skill */
            skill: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Category */
            category: string;
            /** Stage */
            stage: string;
            /** Next Step Definition */
            next_step_definition: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /**
         * WorkflowCompletionDTO
         * @description Completion input with mandatory UI session and one-time nonce fields.
         */
        WorkflowCompletionDTO: {
            /** @default false */
            completed: components["schemas"]["JsonValue"];
            /** @default 0 */
            expected_version: components["schemas"]["JsonValue"];
            /** @default  */
            session_id: components["schemas"]["JsonValue"];
            /** @default  */
            nonce_id: components["schemas"]["JsonValue"];
            /** @default  */
            nonce_hash: components["schemas"]["JsonValue"];
            idempotency_key?: components["schemas"]["JsonValue"] | null;
        };
        /**
         * WorkflowCompletionResultDTO
         * @description Legacy-compatible workflow projection with idempotency visibility.
         */
        WorkflowCompletionResultDTO: {
            /** Id */
            id: string;
            /** Context Id */
            context_id: string;
            /** Work Package Id */
            work_package_id: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Completed */
            is_completed: boolean;
            /** Completion Row Version */
            completion_row_version: number;
            /** Completed At */
            completed_at: string | null;
            /** Completed By */
            completed_by: string | null;
            /** Area Id */
            area_id: string | null;
            /** Template Id */
            template_id: string | null;
            /** Skill Id */
            skill_id: string | null;
            /** Selection Status */
            selection_status: string;
            /** Selection Reason */
            selection_reason: string | null;
            /** Author Confirmed */
            author_confirmed: boolean;
            /** Mode */
            mode: string;
            /** Row Version */
            row_version: number;
            /** Archived */
            archived: boolean;
            /** Inputs Json */
            inputs_json: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Idempotent */
            idempotent: boolean;
            /** Has Achievement Cards */
            has_achievement_cards: boolean;
        };
        /**
         * WorkflowDTO
         * @description Complete workflow row plus the legacy achievement card projection.
         */
        WorkflowDTO: {
            /** Id */
            id: string;
            /** Context Id */
            context_id: string;
            /** Work Package Id */
            work_package_id: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Completed */
            is_completed: boolean;
            /** Completion Row Version */
            completion_row_version: number;
            /** Completed At */
            completed_at: string | null;
            /** Completed By */
            completed_by: string | null;
            /** Area Id */
            area_id: string | null;
            /** Template Id */
            template_id: string | null;
            /** Skill Id */
            skill_id: string | null;
            /** Selection Status */
            selection_status: string;
            /** Selection Reason */
            selection_reason: string | null;
            /** Author Confirmed */
            author_confirmed: boolean;
            /** Mode */
            mode: string;
            /** Row Version */
            row_version: number;
            /** Archived */
            archived: boolean;
            /** Inputs Json */
            inputs_json: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Achievement Cards */
            achievement_cards: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
        };
        /** WorkflowListDTO */
        WorkflowListDTO: {
            /** Workflows */
            workflows: components["schemas"]["WorkflowDTO"][];
            progress: components["schemas"]["ProgressDTO"];
        };
        /**
         * WorkflowRecordDTO
         * @description Workflow row without the heavier card projection.
         */
        WorkflowRecordDTO: {
            /** Id */
            id: string;
            /** Context Id */
            context_id: string;
            /** Work Package Id */
            work_package_id: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Completed */
            is_completed: boolean;
            /** Completion Row Version */
            completion_row_version: number;
            /** Completed At */
            completed_at: string | null;
            /** Completed By */
            completed_by: string | null;
            /** Area Id */
            area_id: string | null;
            /** Template Id */
            template_id: string | null;
            /** Skill Id */
            skill_id: string | null;
            /** Selection Status */
            selection_status: string;
            /** Selection Reason */
            selection_reason: string | null;
            /** Author Confirmed */
            author_confirmed: boolean;
            /** Mode */
            mode: string;
            /** Row Version */
            row_version: number;
            /** Archived */
            archived: boolean;
            /** Inputs Json */
            inputs_json: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /**
         * WorkflowSelectionDTO
         * @description Selection input keyed by work package inside one context.
         */
        WorkflowSelectionDTO: {
            /** @default  */
            wp_id: components["schemas"]["JsonValue"];
            /** @default  */
            selection_status: components["schemas"]["JsonValue"];
            reason?: components["schemas"]["JsonValue"] | null;
            /** @default false */
            author_confirmed: components["schemas"]["JsonValue"];
            /** @default 0 */
            expected_version: components["schemas"]["JsonValue"];
        };
        /**
         * APIErrorDTO
         * @description Stable problem payload used by every target API error response.
         */
        APIErrorDTO: {
            /**
             * Code
             * @example INVALID_INPUT
             */
            code: string;
            /**
             * Detail
             * @example 请求参数无效
             */
            detail: string;
            /**
             * Requestid
             * @example 5f0d5b3a6cbf4f21916d1bd5f47b28c1
             */
            requestId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessDTO"];
                };
            };
            /** @description PostgreSQL or schema is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    catalog_api_v1_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogDTO"];
                };
            };
        };
    };
    research_workflow_map_api_v1_research_workflow_map_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchWorkflowMapDTO"];
                };
            };
            /** @description Workflow map configuration is unavailable or invalid */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload_achievement_attachment_api_v1_achievement_cards__card_id__attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementAttachmentDTO"];
                };
            };
            /** @description Achievement card does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Attachment filename or deleted-card state conflicts */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Attachment file exceeds limits or fails validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Attachment database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    achievement_attachment_detail_api_v1_achievement_attachments__attachment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementAttachmentDTO"];
                };
            };
            /** @description Attachment or artifact file does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Attachment integrity verification failed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Attachment database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    download_achievement_attachment_api_v1_achievement_attachments__attachment_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Attachment or artifact file does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Attachment integrity verification failed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Attachment database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    preview_achievement_attachment_api_v1_achievement_attachments__attachment_id__preview_get: {
        parameters: {
            query?: {
                representation?: string;
            };
            header?: never;
            path: {
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Attachment or preview artifact does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Attachment integrity verification failed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Attachment preview is unavailable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Attachment database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    achievement_attachment_image_api_v1_achievement_attachments__attachment_id__images__index__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachment_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Attachment or preview artifact does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Attachment integrity verification failed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Attachment preview is unavailable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Attachment database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    prepare_context_deletion_api_v1_contexts__context_id__deletion_prepare_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextDeletionPrepareDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextDeletionPrepareResultDTO"];
                };
            };
            /** @description Request body is not a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Context does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Context version changed or a deletion is already active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Deletion preparation input is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Deletion database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    commit_context_deletion_api_v1_contexts__context_id__deletion_commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextDeletionCommitDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextDeletionCommitResultDTO"];
                };
            };
            /** @description Request body is not a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Deletion ticket is invalid or bound to another session */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Context or deletion operation does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Deletion ticket expired, was replayed, or conflict requires preparation again */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Deletion database or artifact dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    list_contexts_api_v1_contexts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextListDTO"];
                };
            };
            /** @description Context database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    create_context_api_v1_contexts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedContextDTO"];
                };
            };
            /** @description Request body is not a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Context input is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Context database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    context_detail_api_v1_contexts__context_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextDTO"];
                };
            };
            /** @description Context does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Context database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    get_disclosure_preferences_api_v1_contexts__context_id__disclosure_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisclosurePreferenceListDTO"];
                };
            };
            /** @description Request body is not a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Context or disclosure subject does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Disclosure preference version changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Disclosure input is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Disclosure database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    upsert_disclosure_preference_api_v1_contexts__context_id__disclosure_preferences_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisclosurePreferenceDTO"];
                };
            };
            /** @description Request body is not a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Context or disclosure subject does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Disclosure preference version changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Disclosure input is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Disclosure database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    create_ui_session_api_v1_ui_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UiSessionIssueResultDTO"];
                };
            };
            /** @description Request body is not a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description UI session input is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description UI session database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    create_completion_authorization_api_v1_workflows__workflow_id__completion_authorization_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionAuthorizationResultDTO"];
                };
            };
            /** @description Request body is not a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description UI session is invalid */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Workflow does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Workflow version changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Completion authorization input is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Workflow authorization database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    context_workflows_api_v1_contexts__context_id__workflows_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowListDTO"];
                };
            };
            /** @description Context does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Workflow database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    create_achievement_card_api_v1_achievement_cards_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementCardDTO"];
                };
            };
            /** @description Request body is not a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Workflow does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Workflow ownership or week item binding conflicts */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Achievement card input is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Achievement card database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    create_achievement_card_compat_api_achievement_cards_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementCardDTO"];
                };
            };
            /** @description Request body is not a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Workflow does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Workflow ownership or week item binding conflicts */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Achievement card input is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Achievement card database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    update_achievement_card_api_v1_achievement_cards__card_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AchievementCardUpdateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementCardDTO"];
                };
            };
            /** @description Request body is not a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Achievement card does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Achievement card version changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Achievement card input is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Achievement card database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    delete_achievement_card_api_v1_achievement_cards__card_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AchievementCardDeleteDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDeleteResultDTO"];
                };
            };
            /** @description Request body is not a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Achievement card does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Delete confirmation or card version conflicts */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Delete input is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Achievement card database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    set_achievement_card_importance_api_v1_contexts__context_id__workflows__workflow_id__achievement_cards__card_id__importance_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context_id: string;
                workflow_id: string;
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AchievementCardImportanceDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardImportanceResultDTO"];
                };
            };
            /** @description Card or owning context and workflow does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Achievement card version changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Importance input is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Achievement card database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    set_workflow_selection_api_v1_contexts__context_id__workflow_selection_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowSelectionDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRecordDTO"];
                };
            };
            /** @description Request body is not a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Work package or workflow does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Workflow version changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Selection status or author confirmation is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Workflow database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
    set_workflow_completion_api_v1_workflows__workflow_id__completion_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCompletionDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowCompletionResultDTO"];
                };
            };
            /** @description Request body is not a JSON object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description UI session or completion nonce is invalid */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Workflow does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Workflow version changed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Completion input is invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
            /** @description Workflow database dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["APIErrorDTO"];
                };
            };
        };
    };
}
